[package]
name = "GenkaiEraRs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.196"
serde_json = "1.0.113"
serenity = "0.12.0"
tokio = "1.35.1"
